sonar.projectKey=backend-rust
sonar.projectName=Backend Rust
sonar.sources=src
sonar.tests=tests
sonar.exclusions=tests/**,**/*_test.rs,**/*.test.rs
sonar.rust.coverage.reportPaths=cobertura.xml
sonar.rust.clippy.reportPaths=clippy-report.json
