sonar.projectKey=job-service-rust
sonar.projectName=Job Service Rust
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/target/**,**/coverage/**
sonar.rust.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
